### ISSUE TITLE
Build fails on the ROS buildfarm

### ISSUE THREAD

**Issue by mintar** [uos/basler_tof#1]
The builds fail on the ROS buildfarm (e.g., [here](http://build.ros.org/job/Idev__basler_tof__ubuntu_trusty_amd64/)). The reason is that it's missing the GenTL library from basler-tof-driver. The library cannot be included in this repo since it's not open source.

In Travis, I just use wget to set it up: [.travis.yml:15-17](https://github.com/uos/basler_tof/blob/810c8aee1b396d1ad46e785c1aca3859adf360f9/.travis.yml#L15-L17).

@dirk-thomas : Is there a way to do this on the ROS buildfarm?

**Comment by dirk-thomas** [comment]
The package needs to be buildable using the CMake file provided. While you can add this download step to the CMake configure step (see http://docs.ros.org/api/catkin/html/dev_guide/generated_cmake_api.html#catkin-download) we don't recommend relying on external resources since you can't assume that a user has internet connectivity when trying to build your package (see note in the referenced doc). If you can't add the library into your repo that might the only way though.

**Comment by mintar** [comment]
Ok, thanks!
